_wandb:
    value:
        cli_version: 0.22.2
        e:
            020cau7vgasbk849auveco6pkucflg0r:
                args:
                    - --nusc_data_path
                    - /home/zl3466/Documents/dataset/NuScenes
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "125389357056"
                        used: "99911831552"
                email: zl3466@nyu.edu
                executable: /home/zl3466/anaconda3/envs/voformer/bin/python
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-f93bd6b3-9094-96c0-fa9f-f24b0f4ff1d2
                host: zhiheng-ROG
                memory:
                    total: "67222511616"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: /home/zl3466/Documents/cmu/10623/proj/train.py
                python: CPython 3.9.24
                root: /home/zl3466/Documents/cmu/10623/proj
                startedAt: "2025-10-24T04:26:54.784849Z"
                writerId: 020cau7vgasbk849auveco6pkucflg0r
        m: []
        python_version: 3.9.24
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
            "3":
                - 13
                - 16
            "4": 3.9.24
            "5": 0.22.2
            "6": 4.57.1
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 1
learning_rate:
    value: "1e-5"
model_name:
    value: Qwen/Qwen2.5-VL-3B-Instruct
num_epochs:
    value: 10
num_input_frames:
    value: 8
num_input_poses:
    value: 8
num_target_poses:
    value: 16
pose_dim:
    value: 3
quantization_range:
    value: 2
vocab_size:
    value: 1000
